### ISSUE TITLE
Plot error

### ISSUE THREAD

**Issue by gerald4** [sherbold/autorank#10]
Hi!
I ran autorank to rank algorithms and the last sentence of the result is: "Based on the post-hoc Nemenyi test, we assume that there are no significant differences within the following groups: sobel and random; random and guidedbackprop; guidedbackprop and smoothgrad; smoothgrad and rise; rise, scorecam, and layercam. All other differences are significant.".
However, this does not reflect on the plot (see figure). It seems that the plot function has a problem
![plot](https://user-images.githubusercontent.com/25696977/152769508-0b8286ff-7a02-4f32-93f1-01e59f39c4f7.png)
.

**Comment by sherbold** [comment]
Could you provide data to replicate this?

**Comment by vnmabus** [comment]
I just negated `reverse` in the call to `get_sorted_rank_groups` and it worked for my case... not sure if in general.

**Comment by sherbold** [comment]
The issue seems to be that the sorting from one of the used libraries is unreliable or was changed at some point. At least this is what it looks like based on what @AlexandreAbraham found in #11. When I have time (so definitively after the current lecture period), I will look at rewriting that part to not assume sorting behavior, hoping that this would then be fixed.

**Comment by sherbold** [comment]
This should now be fixed. I will push a release in the next days as well. If the issue still exists, please reopen.
